### ISSUE TITLE
Would really like Powershell pasting.

### ISSUE THREAD

**Issue by euroclydon37** [krzkaczor/hyperterm-paste#11]
Instead of concatenating multiline commands with `&&`, when using Powershell, it should be with semicolons. This would be awesome. If I have time, I might do a pull request.

**Comment by krzkaczor** [comment]
@euroclydon37 good idea! @miccarr created PR with adding support for fish shell which is great but I think we need to refactor it a little bit to support other shells easily.

**Comment by krzkaczor** [comment]
solved by https://github.com/krzkaczor/hyperterm-paste/pull/17
