### ISSUE TITLE
Using plugin on WSL issue

### ISSUE THREAD

**Issue by qaraluch** [krzkaczor/hyperterm-paste#13]
On "Windows Subsystem for Linux" (WSL) sometime you pasting text with FN end line which is not properly sanitize by plugin's function and therefore executes the line.

**Comment by qaraluch** [comment]
Different story is that after paste clean string and hit the enter first time hyper shows "^M" chars and you have to hit the enter again. I don't know what it really is.

**Comment by krzkaczor** [comment]
Released with 1.1.1
