### ISSUE TITLE
doesn't seem to work on Hyper 2.0.2

### ISSUE THREAD

**Issue by blacktop** [krzkaczor/hyperterm-paste#16]
doesn't remove leading `$`

**Comment by krzkaczor** [comment]
Hey, good to know. Currently, still 1.x is stable, right? I just downloaded hyper from zeit page and it's 1.4.8.

PR would be appreciated :) - I don't use hyper personally anymore...

**Comment by krzkaczor** [comment]
I believe this is connected with: https://github.com/zeit/hyper/issues/2290

**Comment by blacktop** [comment]
yeah it looks like hyper-awesome is working on marking things as supported by the 2.0.2 beta or current stable 1.4.*
