### ISSUE TITLE
hyperterm-paste is not working in hyper 3.0.2

### ISSUE THREAD

**Issue by Staubgeborener** [krzkaczor/hyperterm-paste#25]
Is this project still under development?
I am using the hyper version 3.0.2 and hyperterm-paste don't seem to work here. Leading whitespaces will not be removed, also leading $, etc. Hyperterm-paste is in my plugins-section under .hyper.js and also the node-module are in place:
```shell
~/.hyper_plugins/node_modules/hyperterm-paste   
❯ ls
LICENSE  package.json  README.md  src
```

**Comment by krzkaczor** [comment]
Hey, no this is not maintained anymore. Feel free to fork.
