### ISSUE TITLE
Usage with FISH shell

### ISSUE THREAD

**Issue by CrashyBang** [krzkaczor/hyperterm-paste#3]
With [FISH shell](https://fishshell.com/) only one `&` is needed on multi-line pastes would it be possible to add this in based on the shell?

Cheers.

**Comment by krzkaczor** [comment]
Thanks for noting it. I think that having option to configure it would be perfect. I will fix when i have time.

**Comment by CrashyBang** [comment]
@krzkaczor awesome looking forward to it, if there is any testing you want done let me know.

**Comment by niieani** [comment]
Yeah, had the same idea. Actually it would be even better if you could convert the bash syntax to fish syntax on the fly. Note the proper syntax for `command && command && command` is: `command; and command; and command`, similarly for OR you use `; or` instead of `||`.

**Comment by e-beach** [comment]
Looking to fix this. I love fish but their decision to not support `&&` was terrible for basically all their users.

**Comment by krzkaczor** [comment]
Solved by https://github.com/krzkaczor/hyperterm-paste/pull/17. Released with `hyperterm-paste@1.1.2`

**Comment by krzkaczor** [comment]
and oh btw. I think that ENV variable is awful solution to this problem but I couldnt just add custom key to config (it's parsed or something and I can't acces it later). If anyone has better idea how to implement it hit me up ;)

**Comment by niieani** [comment]
Awesome addition. Note that fish has also other differences, like OR (`||`) should be `; or`. A full blown conversion (even if limited) would be fantastic.
