### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by stereokai** [krzkaczor/hyperterm-paste#5]
@krzkaczor, Hyper 1.0.0 was released with Windows support.

This attractive plugin doesn't seem to work. It doesn't throw any errors to the console.

Let's try and work it out together?

**Comment by krzkaczor** [comment]
Hey! Thanks for this bug report. Let me work on this during the weekend. I will find VM with Windows ;)

**Comment by stereokai** [comment]
Thank you very much :)

**Comment by krzkaczor** [comment]
I am sorry I can't even install hyper term currently on windows :/ Seems full of bugs. I don't have much time today to play with it.

**Comment by stereokai** [comment]
What do you mean? I am using it daily..

**Comment by thangnqs** [comment]
I don't copy and pasted on Windows, not working, I use version hyper 1.0.1.

**Comment by maetthew** [comment]
Would love to get this working.

@krzkaczor I bet this has to do with your looking for e.MetaKey which on Windows is the WinKey I presume. Still doesn't work to paste to paste with WinKey+V. From Googling it looks like Winkey+V is used in Windows to cycle notifications in Action Centre.

I *think* this could be resolved with a switch or if statement that checks what operating system we're running. If you agree, I could probably solve this for you. I'm noob with JS and NodeJS and I have not digged into the workings of Hyper. Do you think this will suffice?

**Comment by krzkaczor** [comment]
@maetthew if / switch seems like a okay solution for me. Please if you can fix it create PR :) As I said before I don't have access to windows version of hyper.

**Comment by maetthew** [comment]
@krzkaczor I will see what I can do. I have a little bit of time right now and will investigate a little, then no time for basically 2 weeks.

**Comment by bboysathish** [comment]
https://github.com/krzkaczor/hyperterm-paste/blob/master/src/index.js#L19 
This is the issue, metaKey will be always false in windows, except for `winkey`.
May be need to find way to handle paste event generic.

**Comment by stereokai** [comment]
@krzkaczor Still doesn't work for me :)
@bboysathish what shell did you use to test this out on your windows machine? (Does it even matter?)

**Comment by bboysathish** [comment]
@stereokai Normal command shell, 
I tested using below steps
1. open hyper
2.  install hyperterm-paste
3. add it to plugins
4. copy something
5. paste it using (Ctrl + V) for windows
